#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SearchService.WebAPI/SearchService.WebAPI.csproj", "SearchService.WebAPI/"]
COPY ["CommonInitializer/CommonInitializer.csproj", "CommonInitializer/"]
COPY ["CommomFilters/CommomFilters.csproj", "CommomFilters/"]
COPY ["CommomJWT/CommomJWT.csproj", "CommomJWT/"]
COPY ["CommomInterface/CommomInterface.csproj", "CommomInterface/"]
COPY ["CommonInfrastructure/CommonInfrastructure.csproj", "CommonInfrastructure/"]
COPY ["CommonDomain/DomainCommon.csproj", "CommonDomain/"]
COPY ["CommonMiddleWare/CommonMiddleWare.csproj", "CommonMiddleWare/"]
COPY ["Commons/CommonHelpers.csproj", "Commons/"]
COPY ["EventBus/EventBus.csproj", "EventBus/"]
COPY ["CommomConst/CommomConst.csproj", "CommomConst/"]
COPY ["SearchService.Domain/SearchService.Domain.csproj", "SearchService.Domain/"]
COPY ["SearchService.Infrastructure/SearchService.Infrastructure.csproj", "SearchService.Infrastructure/"]
RUN dotnet restore "SearchService.WebAPI/SearchService.WebAPI.csproj"
COPY . .
WORKDIR "/src/SearchService.WebAPI"
RUN dotnet build "SearchService.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SearchService.WebAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SearchService.WebAPI.dll"]